twisted.python.failure.Failure's __repr__ now includes the exception message.
